spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: product
    password: product123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update